Imports System.Text
Module BackDataCode

    Dim DBMODE As String
    Dim strQuery As StringBuilder

    Public Function EntryData_FinishInvoice_Challan_Selection_System(ByVal Str_In_Challan_Book As String, ByVal AccountCode As String, ByVal BillDate As String, ByVal Book_Transaction_Type As String, ByVal BookCode As String) As String
        strQuery = New StringBuilder
        With strQuery
            If Book_Transaction_Type = "PURCHASE" Or Book_Transaction_Type = "SALES G.R." Then
                .Append(" SELECT ")
                .Append(" SPACE(1) AS MARK, ")
                .Append(" Z.PACK_SLIP_NO AS CHALLANNO, ")
                .Append(" (Z.PACK_SLIP_DATE) AS F_CHALLANDATE, ")
                .Append(" Z.CUTNAME, ")
                .Append(" Z.FABRIC_ITEMNAME, ")
                .Append(" Z.PCS, ")
                .Append(" Z.MTR_WEIGHT, ")
                .Append(" IIF(Z.CUTTYPE='FENT',Z.MTR_WEIGHT,Z.WEIGHT) AS WEIGHT, ")
                .Append(" Z.ACOFNAME, ")
                .Append(" Z.TRANSPORTNAME, ")
                .Append(" Z.RATEON, ")
                .Append(" Z.TRANSPORTCODE, ")
                .Append(" Z.ACOFCODE, ")
                .Append(" Z.CUTCODE, ")
                .Append(" Z.ITEMCODE, ")
                .Append(" Z.BOOKVNO, ")
                .Append(" Z.ACCOUNTCODE, ")
                .Append(" Z.DESPATCHCODE, ")
                .Append(" Z.ACCOUNTNAME, ")
                .Append(" Z.DESPATCH, ")
                .Append(" '' AS AGENTCODE, ")
                .Append(" '' AS AGENTNAME, ")
                .Append(" Z.RATE,")
                .Append(" Z.OFFERNO, ")
                .Append(" '' AS DESCR,Z.OFFERBOOKVNO ")
                .Append(" FROM ")
                .Append(" ( ")
                .Append(" SELECT A.OFFERNO,A.OFFERBOOKVNO,A.ENTRYNO,A.PACK_SLIP_NO, A.PACK_SLIP_DATE, SUM(A.PCS) AS PCS, ")
                .Append(" SUM(A.MTR_WEIGHT) AS MTR_WEIGHT, SUM(A.WEIGHT) AS WEIGHT, A.RATEON,")
                .Append(" A.ITEMCODE, A.CUTCODE, A.DESPATCHCODE, ")
                .Append(" A.ACCOUNTCODE, A.TRANSPORTCODE, A.ACOFCODE, A.BOOKVNO, A.RATE,")
                .Append(" B.ACCOUNTNAME, C.ITENNAME, D.CUTNAME, ")
                .Append(" E.CITYNAME AS DESPATCH, F.TRANSPORTNAME, G.ACOFNAME,D.CUTTYPE ")
                .Append(" FROM ((((((TRNPACKINGSLIP AS A ")
                .Append(" LEFT JOIN TRNINVOICEDETAIL ON A.BOOKVNO=TRNINVOICEDETAIL.CHALLANBOOKVNO) ")
                .Append(" LEFT JOIN MstMasterAccount AS B ON A.ACCOUNTCODE=B.ACCOUNTCODE) ")
                .Append(" LEFT JOIN  MSTFABRICITEM AS C ON A.ITEMCODE=C.ID) ")
                .Append(" LEFT JOIN MstCutMaster AS D ON A.CUTCODE=D.CUTCODE) ")
                .Append(" LEFT JOIN MSTCITY AS E ON A.DESPATCHCODE=E.CITYCODE) ")
                .Append(" LEFT JOIN MSTTRANSPORT AS F ON A.TRANSPORTCODE=F.ID) ")
                .Append(" LEFT JOIN Mst_Acof_Supply AS G ON A.ACOFCODE=G.ID  ")
                .Append(" WHERE 1=1 And TRNINVOICEDETAIL.CHALLANBOOKVNO Is Null ")
                .Append(" And (CUTCODE1='' Or CUTCODE1 Is Null) And (ITEMCODE1='' Or ITEMCODE1 Is Null)  ")
                .Append(" AND A.ACCOUNTCODE='" & AccountCode & "'")
                .Append(" AND A.PACK_SLIP_DATE<='" & BillDate & "' ")
                .Append(Str_In_Challan_Book)
                .Append(" GROUP BY A.OFFERNO,A.OFFERBOOKVNO,A.ENTRYNO,A.PACK_SLIP_NO, A.PACK_SLIP_DATE, A.RATEON, A.ITEMCODE, A.CUTCODE, ")
                .Append(" A.DESPATCHCODE, A.ACCOUNTCODE, A.TRANSPORTCODE, A.ACOFCODE, A.BOOKVNO, A.RATE, ")
                .Append(" B.ACCOUNTNAME, C.ITENNAME, D.CUTNAME, E.CITYNAME, F.TRANSPORTNAME, G.ACOFNAME,D.CUTTYPE ")
                .Append(" UNION ALL ")
                .Append(" SELECT A.OFFERNO,A.OFFERBOOKVNO,A.ENTRYNO,A.CHALLANNO AS PACK_SLIP_NO, A.Bill_Chl_Date AS PACK_SLIP_DATE, SUM(A.PCS) AS PCS, ")
                .Append(" SUM(A.MTR) AS MTR_WEIGHT, CDBL(0) AS WEIGHT, '' AS RATEON,")
                .Append(" A.ITEMCODE, A.CUTCODE, A.DESPATCHCODE, ")
                .Append(" A.ACCOUNTCODE, A.TRANSPORTCODE, A.ACOFCODE, A.BOOKVNO,CDBL(0) AS RATE,")
                .Append(" B.ACCOUNTNAME, C.ITENNAME, D.CUTNAME, ")
                .Append(" E.CITYNAME AS DESPATCH, F.TRANSPORTNAME, G.ACOFNAME,D.CUTTYPE ")
                .Append(" FROM ((((((TRNGRADING AS A ")
                .Append(" LEFT JOIN TRNINVOICEDETAIL ON A.BOOKVNO=TRNINVOICEDETAIL.CHALLANBOOKVNO) ")
                .Append(" LEFT JOIN MstMasterAccount AS B ON A.ACCOUNTCODE=B.ACCOUNTCODE) ")
                .Append(" LEFT JOIN  MSTFABRICITEM AS C ON A.ITEMCODE=C.ID) ")
                .Append(" LEFT JOIN MstCutMaster AS D ON A.CUTCODE=D.CUTCODE) ")
                .Append(" LEFT JOIN MSTCITY AS E ON A.DESPATCHCODE=E.CITYCODE) ")
                .Append(" LEFT JOIN MSTTRANSPORT AS F ON A.TRANSPORTCODE=F.ID) ")
                .Append(" LEFT JOIN Mst_Acof_Supply AS G ON A.ACOFCODE=G.ID  ")
                .Append(" WHERE 1=1 And TRNINVOICEDETAIL.CHALLANBOOKVNO Is Null ")
                .Append(" AND A.ACCOUNTCODE='" & AccountCode & "'")
                .Append(" AND A.Bill_Chl_Date<='" & BillDate & "' ")
                .Append(Str_In_Challan_Book)
                .Append(" GROUP BY A.OFFERNO,A.OFFERBOOKVNO,A.ENTRYNO,A.CHALLANNO, A.Bill_Chl_Date,A.ITEMCODE, A.CUTCODE, ")
                .Append(" A.DESPATCHCODE, A.ACCOUNTCODE, A.TRANSPORTCODE, A.ACOFCODE, A.BOOKVNO, ")
                .Append(" B.ACCOUNTNAME, C.ITENNAME, D.CUTNAME, E.CITYNAME, F.TRANSPORTNAME, G.ACOFNAME,D.CUTTYPE ")
                .Append(" ) AS Z ")
                .Append(" WHERE 1=1 AND Z.ITEMCODE<>'' ")
                .Append(" ORDER BY Z.ENTRYNO, Z.FABRIC_ITEMNAME,Z.CUTNAME ")
            Else
                If BookCode = "0001-000000292" Then
                    .Append(" SELECT ")
                    .Append(" SPACE(1) AS MARK, ")
                    .Append(" A.DESPCHALLANNO AS CHALLANNO, ")
                    .Append(" (A.DESPCHALLANDATE) AS F_CHALLANDATE, ")
                    .Append(" 'ROLL' AS CUTNAME, ")
                    .Append(" IIF(A.DESPDESCR='',C.ITENNAME,A.DESPDESCR) AS FABRIC_ITEMNAME, ")
                    .Append(" COUNT(A.LUMP_NO) AS PCS, ")
                    .Append(" SUM(A.PMTR) AS MTR_WEIGHT, ")
                    .Append(" SUM(A.FWEIGHT) AS WEIGHT, ")
                    .Append(" A.DespHeaderRemark AS ACOFNAME, ")
                    .Append(" D.TRANSPORTNAME, ")
                    .Append(" 'MTR' AS RATEON, ")
                    .Append(" A.DESPTRANSPORTCODE, ")
                    .Append(" '0000-000000001' AS ACOFCODE, ")
                    .Append(" '0000-000000016' AS CUTCODE, ")
                    .Append(" A.ID AS ITEMCODE, ")
                    .Append(" A.DESPBOOKVNO AS BOOKVNO, ")
                    .Append(" A.DESPACCOUNTCODE, ")
                    .Append(" E.CITYCODE AS DESPATCHCODE, ")
                    .Append(" B.ACCOUNTNAME, ")
                    .Append(" E.CITYNAME AS DESPATCH, ")
                    .Append(" '' AS AGENTCODE, ")
                    .Append(" '' AS AGENTNAME, ")
                    .Append(" 0 AS RATE, ")
                    .Append(" A.DESPOFFERNO AS OFFERNO, ")
                    .Append(" A.GRADE AS DESCR,A.DESPOFFERBOOKVNO AS OFFERBOOKVNO ")
                    .Append(" FROM ((((TRNDENIMFOLDING AS A ")
                    .Append(" LEFT JOIN TRNINVOICEDETAIL ON A.DESPBOOKVNO=TRNINVOICEDETAIL.CHALLANBOOKVNO) ")
                    .Append(" LEFT JOIN MstMasterAccount AS B ON A.DESPACCOUNTCODE=B.ACCOUNTCODE) ")
                    .Append(" LEFT JOIN MSTFABRICITEM AS C ON A.ID=C.ID) ")
                    .Append(" LEFT JOIN MSTTRANSPORT AS D ON A.DESPTRANSPORTCODE=D.TRANSPORTCODE) ")
                    .Append(" LEFT JOIN MSTCITY AS E ON B.CITYCODE=E.CITYCODE ")
                    .Append(" WHERE 1=1 And TRNINVOICEDETAIL.CHALLANBOOKVNO Is Null ")
                    .Append(" AND A.DESPCHALLANNO<>0 ")
                    .Append(" AND A.DESPACCOUNTCODE='" & AccountCode & "'")
                    .Append(" GROUP BY ")
                    .Append(" E.CITYCODE,A.DESPOFFERNO,A.DESPDESCR, ")
                    .Append(" A.DESPOFFERBOOKVNO,A.DespHeaderRemark, ")
                    .Append(" A.DESPCHALLANNO , ")
                    .Append(" A.DESPCHALLANDATE, ")
                    .Append(" C.ITENNAME, ")
                    .Append(" D.TRANSPORTNAME, ")
                    .Append(" A.DESPTRANSPORTCODE, ")
                    .Append(" A.ID, ")
                    .Append(" A.DESPBOOKVNO, ")
                    .Append(" A.DESPACCOUNTCODE, ")
                    .Append(" B.ACCOUNTNAME, ")
                    .Append(" A.GRADE,E.CITYNAME ")
                    .Append(" ORDER BY A.DESPCHALLANNO, C.ITENNAME,A.GRADE ")
                Else
                    .Append(" SELECT ")
                    .Append(" SPACE(1) AS MARK, ")
                    .Append(" Z.PACK_SLIP_NO AS CHALLANNO, ")
                    .Append(" (Z.PACK_SLIP_DATE) AS F_CHALLANDATE, ")
                    .Append(" Z.CUTNAME, ")
                    .Append(" Z.FABRIC_ITEMNAME, ")
                    .Append(" Z.PCS, ")
                    .Append(" Z.MTR_WEIGHT, ")
                    .Append(" IIF(Z.CUTTYPE='FENT',Z.MTR_WEIGHT,Z.WEIGHT) AS WEIGHT, ")
                    .Append(" Z.ACOFNAME, ")
                    .Append(" Z.TRANSPORTNAME, ")
                    .Append(" Z.RATEON, ")
                    .Append(" Z.TRANSPORTCODE, ")
                    .Append(" Z.ACOFCODE, ")
                    .Append(" Z.CUTCODE, ")
                    .Append(" Z.ITEMCODE, ")
                    .Append(" Z.BOOKVNO, ")
                    .Append(" Z.ACCOUNTCODE, ")
                    .Append(" Z.DESPATCHCODE, ")
                    .Append(" Z.ACCOUNTNAME, ")
                    .Append(" Z.DESPATCH, ")
                    .Append(" '' AS AGENTCODE, ")
                    .Append(" '' AS AGENTNAME, ")
                    .Append(" Z.RATE,")
                    .Append(" Z.OFFERNO, ")
                    .Append(" '' AS DESCR,Z.OFFERBOOKVNO,Z.HEADERREMARK,Z.BALE_WEIGHT,Z.PARTYOFFERNO ")
                    .Append(" FROM ")
                    .Append(" ( ")
                    .Append(" SELECT A.PARTYOFFERNO,A.OFFERNO,A.OFFERBOOKVNO,A.ENTRYNO,A.PACK_SLIP_NO, A.PACK_SLIP_DATE, SUM(A.PCS) AS PCS, ")
                    .Append(" SUM(A.MTR_WEIGHT) AS MTR_WEIGHT, SUM(A.WEIGHT) AS WEIGHT,A.RATEON, ")
                    .Append(" A.ITEMCODE, A.CUTCODE, A.DESPATCHCODE,A.BALE_WEIGHT, ")
                    .Append(" A.ACCOUNTCODE, A.TRANSPORTCODE, A.ACOFCODE, A.BOOKVNO, A.RATE, ")
                    .Append(" B.ACCOUNTNAME, C.ITENNAME, D.CUTNAME,A.HEADERREMARK, ")
                    .Append(" E.CITYNAME AS DESPATCH, F.TRANSPORTNAME, G.ACOFNAME,D.CUTTYPE ")
                    .Append(" FROM ((((((TRNPACKINGSLIP AS A ")
                    .Append(" LEFT JOIN TRNINVOICEDETAIL ON A.BOOKVNO=TRNINVOICEDETAIL.CHALLANBOOKVNO) ")
                    .Append(" LEFT JOIN MstMasterAccount AS B ON A.ACCOUNTCODE=B.ACCOUNTCODE) ")
                    .Append(" LEFT JOIN  MSTFABRICITEM AS C ON A.ITEMCODE=C.ID) ")
                    .Append(" LEFT JOIN MstCutMaster AS D ON A.CUTCODE=D.CUTCODE) ")
                    .Append(" LEFT JOIN MSTCITY AS E ON A.DESPATCHCODE=E.CITYCODE) ")
                    .Append(" LEFT JOIN MSTTRANSPORT AS F ON A.TRANSPORTCODE=F.ID) ")
                    .Append(" LEFT JOIN Mst_Acof_Supply AS G ON A.ACOFCODE=G.ID  ")
                    .Append(" WHERE 1=1 And TRNINVOICEDETAIL.CHALLANBOOKVNO Is Null ")
                    .Append(" And (CUTCODE1='' Or CUTCODE1 Is Null) And (ITEMCODE1='' Or ITEMCODE1 Is Null)  ")
                    .Append(" AND A.ACCOUNTCODE='" & AccountCode & "'")
                    .Append(" AND A.PACK_SLIP_DATE<='" & BillDate & "' ")
                    .Append(Str_In_Challan_Book)
                    .Append(" GROUP BY A.OFFERNO,A.OFFERBOOKVNO,A.ENTRYNO,A.PACK_SLIP_NO, A.PACK_SLIP_DATE, A.RATEON, A.ITEMCODE, A.CUTCODE, ")
                    .Append(" A.DESPATCHCODE, A.ACCOUNTCODE, A.TRANSPORTCODE, A.ACOFCODE, A.BOOKVNO, A.RATE,A.HEADERREMARK,A.BALE_WEIGHT, ")
                    .Append(" B.ACCOUNTNAME, C.ITENNAME, D.CUTNAME, E.CITYNAME, F.TRANSPORTNAME, G.ACOFNAME,D.CUTTYPE,A.PARTYOFFERNO ")
                    .Append(" UNION ALL   ")
                    .Append(" SELECT *  ")
                    .Append(" FROM ")
                    .Append(" ( ")
                    .Append(" SELECT A.PARTYOFFERNO,A.OFFERNO,A.OFFERBOOKVNO,A.ENTRYNO,A.PACK_SLIP_NO, A.PACK_SLIP_DATE, ")
                    If DBMODE = "SQL" Then
                        .Append(" ROUND(SUM(A.MTR_WEIGHT)/NULLIF(VAL(D.CUTNAME),0),0) AS PCS, ")
                    Else
                        .Append(" ROUND(SUM(A.MTR_WEIGHT)/VAL(D.CUTNAME),0) AS PCS, ")
                    End If
                    .Append(" SUM(A.MTR_WEIGHT) AS MTR_WEIGHT, SUM(A.WEIGHT) AS WEIGHT, A.RATEON, A.ITEMCODE1 AS   ")
                    .Append(" ITEMCODE, A.CUTCODE1 AS CUTCODE, A.DESPATCHCODE,A.BALE_WEIGHT, A.ACCOUNTCODE, A.TRANSPORTCODE, ")
                    .Append(" A.ACOFCODE, A.BOOKVNO, 0 AS RATE, B.ACCOUNTNAME, C.ITENNAME, D.CUTNAME,A.HEADERREMARK, ")
                    .Append(" E.CITYNAME AS DESPATCH, F.TRANSPORTNAME, G.ACOFNAME,D.CUTTYPE ")
                    .Append(" FROM ((((((TRNPACKINGSLIP AS A ")
                    .Append(" LEFT JOIN TRNINVOICEDETAIL ON A.BOOKVNO=TRNINVOICEDETAIL.CHALLANBOOKVNO) ")
                    .Append(" LEFT JOIN MstMasterAccount AS B ON A.ACCOUNTCODE=B.ACCOUNTCODE) ")
                    .Append(" LEFT JOIN MSTFABRICITEM AS C ON A.ITEMCODE1=C.ID) ")
                    .Append(" LEFT JOIN MstCutMaster AS D ON A.CUTCODE1=D.CUTCODE) ")
                    .Append(" LEFT JOIN MSTCITY AS E ON A.DESPATCHCODE=E.CITYCODE) ")
                    .Append(" LEFT JOIN MSTTRANSPORT AS F ON A.TRANSPORTCODE=F.ID) ")
                    .Append(" LEFT JOIN Mst_Acof_Supply AS G ON A.ACOFCODE=G.ID ")
                    .Append(" WHERE 1=1 And TRNINVOICEDETAIL.CHALLANBOOKVNO Is Null ")
                    .Append(" And A.CUTCODE1 Is Not Null ")
                    .Append(" AND A.ACCOUNTCODE='" & AccountCode & "'")
                    .Append(" AND A.PACK_SLIP_DATE<='" & BillDate & "' ")
                    .Append(Str_In_Challan_Book)
                    .Append(" GROUP BY A.PARTYOFFERNO,A.OFFERNO,A.OFFERBOOKVNO,A.ENTRYNO,A.PACK_SLIP_NO, A.PACK_SLIP_DATE, A.RATEON, A.ITEMCODE1, ")
                    .Append(" A.CUTCODE1, A.DESPATCHCODE, A.ACCOUNTCODE,A.HEADERREMARK,A.BALE_WEIGHT, ")
                    .Append(" A.TRANSPORTCODE, A.ACOFCODE, A.BOOKVNO,B.ACCOUNTNAME, ")
                    .Append("  C.ITENNAME, D.CUTNAME, E.CITYNAME, F.TRANSPORTNAME, G.ACOFNAME,D.CUTTYPE ")
                    .Append(" ) ")
                    .Append(" AS Z ")
                    .Append(" ) AS Z ")
                    .Append(" WHERE 1=1 AND Z.ITEMCODE<>'' ")
                    .Append(" ORDER BY Z.ENTRYNO, Z.FABRIC_ITEMNAME,Z.CUTNAME ")
                End If
            End If
        End With
        Return strQuery.ToString
    End Function
End Module
